[metadata]
finding_id = ""
title = "Excessive Ingress Rule Set"
date_discovered = "" # YYYY-MM-DD
date_reported = "" # YYYY-MM-DD
assessment_id = ""
author = ""
client_id = ""
status = "" # E.g., "open", "in_progress", "fixed", "closed"

[classification]
severity = "High" # E.g., "critical", "high", "medium", "low", "informational"
cvss_score = 0.0 # Adjust as needed
cvss_vector = "" # CVSS v3.1/v4 vector string
cwe_id = "" # Numeric portion only
owasp_category = "" 

[affected_components]
system = ""
component = ""
version = ""
location = "" # E.g., URL, file path, code line
endpoints = [] # Array of strings

[details]
description = """While reviewing the configuration of externally facing network devices, the consultant noted that the inbound (or ingress) rule set allowed for an excessive number of applications or ports. This is a critical risk to the organization."""
impact = ""

[reproduction]
steps = [] 
payload = ""

[proof_of_concept]
code = ""
curl_command = ""

[remediation]
recommendation = """It is recommended that <<full_company_name>> adopt a DENY unless required policy for inbound traffic."""

[references]
cve_ids = [] # Array of CVE IDs
external_references = [] # Array of URLs
