[metadata]
finding_id = ""
title = "SNMP Configured with Default Password"
date_discovered = "" # YYYY-MM-DD
date_reported = "" # YYYY-MM-DD
assessment_id = ""
author = ""
client_id = ""
status = "" # E.g., "open", "in_progress", "fixed", "closed"

[classification]
severity = "High" # E.g., "critical", "high", "medium", "low", "informational"
cvss_score = 0.0 # Adjust as needed
cvss_vector = "" # CVSS v3.1/v4 vector string
cwe_id = "" # Numeric portion only
owasp_category = "" 

[affected_components]
system = ""
component = ""
version = ""
location = "" # E.g., URL, file path, code line
endpoints = [] # Array of strings

[details]
description = """Simple Network Management Protocol (SNMP) is a protocol used for managing devices on the network. SNMP uses community stings to access the devices in either read or write mode. While conducting the internal assessment, several devices were discovered with the default SNMP community stings of private and public.
An adversary can use this access to view or change the devices configuration. In some cases passwords and other sensitive information can be extracted from the device. This information is used by an attacker access to other systems within the origination."""
impact = ""

[reproduction]
steps = [
    "The following screenshot shows information obtained from the vulnerable system <IP>: <insert a screenshot>",
    "The following IP addresses were confirmed vulnerable: <insert list of IP addresses>"
]
payload = ""

[proof_of_concept]
code = ""
curl_command = ""

[remediation]
recommendation = """SNMP community stings should be treated the same as account passwords.
It is recommended that <<full_company_name>> implement the following password policy for SNMP configured devices:
  - Use alphanumeric, special characters and spaces to create the pass phrase
  - Use pass phrases at least 32 characters long
  - Change the pass phrase frequently
  - Do not reuse pass phrases"""

[references]
cve_ids = [] # Array of CVE IDs
external_references = [] # Array of URLs
