[metadata]
finding_id = ""
title = "Tomcat Manager with Default or Blank Passwords"
date_discovered = "" # YYYY-MM-DD
date_reported = "" # YYYY-MM-DD
assessment_id = ""
author = ""
client_id = ""
status = "" # E.g., "open", "in_progress", "fixed", "closed"

[classification]
severity = "Critical" # E.g., "critical", "high", "medium", "low", "informational"
cvss_score = 0.0 # Adjust as needed
cvss_vector = "" # CVSS v3.1/v4 vector string
cwe_id = "" # Numeric portion only
owasp_category = "" 

[affected_components]
system = ""
component = ""
version = ""
location = "" # E.g., URL, file path, code line
endpoints = [] # Array of strings

[details]
description = """The Tomcat account ${ACCOUNT_NAME_HERE} was found to be configured with a blank or default password. An adversary could use this account to gain access to the management interface and deploy a malicious web archive file (WAR) file and comprise the system."""
impact = ""

[reproduction]
steps = [] 
payload = ""

[proof_of_concept]
code = ""
curl_command = ""

[remediation]
recommendation = """The default Tomcat account passwords should be configured with a strong pass phrase. The following guide lines can be used for creating a pass phrase:
  - Use alphanumeric, special characters and spaces to create the pass phrase
  - Use pass phrases at least 32 characters long
  - Change the pass phrase frequently
  - Do not reuse pass phrases"""

[references]
cve_ids = [] # Array of CVE IDs
external_references = [] # Array of URLs
