[metadata]
finding_id = ""
title = "Infrastructure: Weak or Default Credentials"
date_discovered = ""
date_reported = ""
assessment_id = ""
author = ""
client_id = ""
status = ""

[classification]
severity = "Critical"
cvss_score = 9.8
cvss_vector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
cwe_id = ""
owasp_category = "A07:2021-Identification and Authentication Failures"

[affected_components]
system = ""
component = ""
version = ""
location = ""
endpoints = []

[details]
description = ""
impact = ""

[reproduction]
steps = [
    "Identify accessible services on infrastructure components that require authentication (e.g., SSH, Telnet, web management interfaces, RDP, database ports).",
    "Attempt to authenticate using common default credential pairs for the identified services and device types (e.g., admin/admin, root/root, cisco/cisco).",
    "Perform dictionary or brute-force attacks against authentication interfaces using lists of common weak passwords.",
    "Check if password policies are weak or non-existent, allowing users to set easily guessable passwords.",
    "Verify if successfully guessed credentials grant privileged access to the system."
]
payload = ""

[proof_of_concept]
code = ""
curl_command = ""

[remediation]
recommendation = "Change all default credentials immediately upon device/service deployment. Enforce strong password policies (length, complexity, history, lockout after failed attempts). Implement multi-factor authentication (MFA) wherever possible, especially for administrative access. Regularly audit for weak or default credentials. Disable or restrict access to unnecessary services and management interfaces."

[references]
cve_ids = []
external_references = [
    "https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/",
    "https://cwe.mitre.org/data/definitions/521.html",
    "https://cwe.mitre.org/data/definitions/1392.html",
    "https://datarecovery.com/rd/default-passwords/"
]
