[metadata]
finding_id = ""
title = "Mobile Hardcoded Credentials/Secrets"
date_discovered = ""
date_reported = ""
assessment_id = ""
author = ""
client_id = ""
status = ""

[classification]
severity = "High"
cvss_score = 7.5
cvss_vector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
cwe_id = ""
owasp_category = "M5: Insufficient Cryptography"

[affected_components]
system = ""
component = ""
version = ""
location = ""
endpoints = []

[details]
description = """A number of services were identified which use a hardcoded password. The risk from this issue is that an attacker could login with an account from a hardcoded password."""
impact = ""

[reproduction]
steps = [
    "Decompile or reverse engineer the mobile application package (APK/IPA).",
    "Search the application's source code, resource files, and configuration files for hardcoded strings that appear to be credentials, API keys, encryption keys, or other secrets.",
    "Common keywords to search for include 'password', 'secret', 'key', 'token', 'apikey', 'auth'.",
    "Analyze identified strings to confirm if they are active and sensitive credentials.",
    "Attempt to use these credentials to access protected resources or services."
]
payload = ""

[proof_of_concept]
code = ""
curl_command = ""

[remediation]
recommendation = ""

[references]
cve_ids = []
external_references = []
