[metadata]
finding_id = ""
title = "Mobile Insecure Data Storage"
date_discovered = ""
date_reported = ""
assessment_id = ""
author = ""
client_id = ""
status = ""

[classification]
severity = "Medium"
cvss_score = 5.5
cvss_vector = "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
cwe_id = ""
owasp_category = "M2: Insecure Data Storage"

[affected_components]
system = ""
component = ""
version = ""
location = ""
endpoints = []

[details]
description = ""
impact = ""

[reproduction]
steps = [
    "Identify where the mobile application stores sensitive data (e.g., credentials, PII, API keys, session tokens).",
    "Common locations include SharedPreferences/NSUserDefaults, SQLite databases, Plist files, files in internal/external storage, Keychain/Keystore (if misused).",
    "Gain access to the device's file system (e.g., via ADB for Android, jailbreak/iFunBox for iOS, or by analyzing app backups).",
    "Examine the identified storage locations for sensitive data stored in clear text, weakly encrypted, or improperly protected.",
    "Verify if encryption keys are hardcoded or easily discoverable within the app's code or files."
]
payload = ""

[proof_of_concept]
code = ""
curl_command = ""

[remediation]
recommendation = "Avoid storing sensitive data on the device whenever possible. If storage is necessary, use platform-provided secure storage mechanisms (e.g., Android Keystore, iOS Keychain) correctly. Encrypt sensitive data at rest using strong encryption algorithms and securely manage encryption keys (avoid hardcoding). Do not store sensitive data in logs or publicly accessible locations like external storage without proper protection. Apply appropriate file permissions."

[references]
cve_ids = []
external_references = [
    "https://owasp.org/www-project-mobile-top-10/2016-risks/m2-insecure-data-storage"
]
