[metadata]
finding_id = ""
title = "Insecure Direct Object References (IDOR)"
date_discovered = ""
date_reported = ""
assessment_id = ""
author = ""
client_id = ""
status = ""

[classification]
severity = "High"
cvss_score = 7.5
cvss_vector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
cwe_id = ""
owasp_category = "A01:2021-Broken Access Control"

[affected_components]
system = ""
component = ""
version = ""
location = ""
endpoints = []

[details]
description = """
The OWASP guide [1] gives the following description for Insecure Direct Object Reference:
Applications frequently use the actual name or key of an object when generating web pages. Applications do not always verify the user is authorized for the target object. This results in an insecure direct object reference flaw. Testers can easily manipulate parameter values to detect such flaws and code analysis quickly shows whether authorization is properly verified."""
impact = ""

[reproduction]
steps = [
    "Identify user-supplied identifiers in requests that reference specific objects (e.g., document_id=123, user_id=456).",
    "Log in as User A and access a resource belonging to User A (e.g., /documents?document_id=123). Note the identifier.",
    "Log in as User B (or attempt unauthenticated access if applicable).",
    "Attempt to access User A's resource by replaying the request with User A's identifier (e.g., /documents?document_id=123).",
    "Observe if the application grants access to User A's resource, indicating an IDOR vulnerability."
]
payload = ""

[proof_of_concept]
code = ""
curl_command = ""

[remediation]
recommendation = """
Use per user or session indirect object references. This prevents attackers from directly targeting unauthorized resources. For example, instead of using the resource’s database key, a drop down list of six resources authorized for the current user could use the numbers 1 to 6 to indicate which value the user selected. The application has to map the per-user indirect reference back to the actual database key on the server.
Check access. Each use of a direct object reference from an untrusted source must include an access control check to ensure the user is authorized for the requested object."""

[references]
cve_ids = []
external_references = [
    "https://www.owasp.org/index.php/Top_10_2010-A4-Insecure_Direct_Object_References"
]
