
[metadata]
finding_id = ""  
title = "Stored Cross-Site Scripting (XSS)"  
date_discovered = ""  
date_reported = ""  
assessment_id = ""  
author = ""  
reviewer = ""  
client_id = ""  
status = ""  
confidentiality = ""  

[classification]
severity = "High"  
cvss_score = 7.2  
cvss_vector = "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N"  
cwe_id = ""  
cwe_name = ""  
owasp_category = "A03:2021-Injection"  

[affected_components]
system = ""  
component = ""  
version = ""  
location = ""  
endpoints = []  
technologies = []  

[details]
description = ""  
impact = ""  
root_cause = ""  

[reproduction]
preconditions = ""  
steps = [
    "Identify an input field that stores and reflects user-supplied data without proper sanitization (e.g., comment section, user profile).",
    "Inject a malicious script payload (e.g., <script>alert('XSS')</script>) into the input field.",
    "Submit the input.",
    "Observe that the script executes when the page displaying the stored data is loaded by any user."
]  
payload = ""  
screenshots = []  

[proof_of_concept]
code = ""  
curl_command = ""  

[remediation]
recommendation = "Implement robust input validation and output encoding for all user-supplied data. Use context-aware encoding (e.g., HTML entity encoding for HTML context, JavaScript encoding for script context). Consider using a Content Security Policy (CSP) to mitigate XSS impact."  
code_fix = ""  
estimated_effort = ""  
timeline = ""  

[references]
cve_ids = []  
external_references = [
    "https://owasp.org/www-community/attacks/xss/",
    "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html"
]  
internal_references = []  

[communication]
disclosed_to = ""  
disclosed_on = ""  
response = ""  

[tracking]
issue_tracker_id = ""  
pull_request = ""  
fix_version = ""  
fix_date = ""  
verification_date = ""  

[compliance]
regulatory_impact = []  
business_impact = ""  
data_breach_risk = false  

[additional_info]
notes = ""  
tags = []  
linked_findings = []  
