[metadata]
finding_id = ""
title = "XML External Entity (XXE) Injection"
date_discovered = ""
date_reported = ""
assessment_id = ""
author = ""
client_id = ""
status = ""

[classification]
severity = "High"
cvss_score = 9.1
cvss_vector = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N"
cwe_id = ""
owasp_category = "A05:2017-XML External Entities (XXE)"

[affected_components]
system = ""
component = ""
version = ""
location = ""
endpoints = []

[details]
description = """An XML External Entity attack is a type of attack against an application that parses XML input. This attack occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser. This attack may lead to the disclosure of confidential data, denial of service, port scanning from the perspective of the machine where the parser is located, and other system impacts."""
impact = ""

[reproduction]
steps = [
    "Identify an XML parser or input point that accepts XML data (e.g., file upload, API endpoint).",
    "Craft an XML payload containing a malicious Document Type Definition (DTD) that defines an external entity pointing to a sensitive local file (e.g., /etc/passwd) or an internal network resource.",
    "Example DTD: <!DOCTYPE foo [ <!ENTITY xxe SYSTEM \"file:///etc/passwd\"> ]>",
    "Reference the external entity within the XML data (e.g., <data>&xxe;</data>).",
    "Submit the malicious XML payload to the application.",
    "Observe if the application's response includes the content of the targeted file or if an out-of-band interaction occurs, indicating successful XXE."
]
payload = ""

[proof_of_concept]
code = ""
curl_command = ""

[remediation]
recommendation = ""

[references]
cve_ids = []
external_references = ["https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing"]
